// src/app/shared/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component, HostListener } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { homeHeader } from 'src/app/core/models/sidebar-model';
import { CommonService } from '../../core/services/common/common.service';
import { DataService } from '../../core/services/data/data.service';
import { SidebarService } from '../../core/services/sidebar/sidebar.service';
import { routes } from 'src/app/core/routes/routes';

@Component({
  selector: 'app-header',
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent {
  public searchField = false;
  public routes = routes;
  public header: homeHeader[];
  base = '';
  page = '';
  last = '';
  isSearch = false;
  isdark = true;
  islight = false;
  overlay = false;
  themeColor = 'light-mode';
  isDropdownOpen = false;
  openDropdownIndex: number | null = null;
  isFixed = false;
  public selectedCTA: 'order' | 'consult' = 'order';

  constructor(
    private common: CommonService,
    private data: DataService,
    public sidebar: SidebarService,
    private router: Router,
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
      this.overlay = false;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
      this.overlay = false;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
      this.overlay = false;
    });
    this.header = this.sidebar.Home_Header;
  }

  public toggleSidebar(): void {
    this.sidebar.openSidebar();
    this.overlay = true;
    document.body.style.overflow = 'hidden';
  }
  public hideSidebar(): void {
    this.sidebar.closeSidebar();
    this.overlay = false;
    document.body.style.overflow = '';
  }
  toggleSubMenu(index: number): void {
    // If the clicked menu is already open, close it
    this.openDropdownIndex = this.openDropdownIndex === index ? null : index;
    this.isDropdownOpen = false;
  }
  toggleSearch() {
    this.searchField = !this.searchField;
  }

  selectCTA(cta: 'order' | 'consult'): void {
    this.selectedCTA = cta;

    if (cta === 'order') {
      this.router.navigate(['/']);
    } else {
      this.router.navigate([routes.vetRegistration]);
    }
  }

  openSearch(): void {
    this.isSearch = !this.isSearch;
  }

  public navigation() {
    this.router.navigate([routes.search1]);
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isFixed = window.pageYOffset > 50;
    const scroll =
      window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;

    const headerOne = document.querySelector('.header-one');
    if (headerOne && scroll > 35) {
      headerOne.classList.add('header-space');
    } else if (headerOne) {
      headerOne.classList.remove('header-space');
    }

    const headerTen = document.querySelector('.header-ten');
    if (headerTen && scroll > 35) {
      headerTen.classList.add('header-space');
    } else if (headerTen) {
      headerTen.classList.remove('header-space');
    }
  }
  ngOnInit(): void {
    const themeColor = localStorage.getItem('themeColor') || 'light-mode';
    this.sidebar.changeThemeColor(themeColor);
  }
  darkMode(): void {
    this.isdark = !this.isdark;
    this.islight = !this.islight;
  }

  onSubmit(): void {
    this.router.navigateByUrl('/search-doctor/search1');
  }
  navigate(): void {
    this.router.navigate([routes.search1]);
  }
}

<header
  class="header header-custom header-default inner-header header-fixed relative"
  [ngClass]="{ fixed: isFixed }"
>
  <div class="container">
    <nav class="navbar navbar-expand-lg header-nav">
      <div class="navbar-header">
        <a (click)="toggleSidebar()" id="mobile_btn" [routerLink]="">
          <i class="fa-solid fa-bars"></i>
        </a>
        <a [routerLink]="'/'" class="navbar-brand logo">
          <img src="assets/img/logo-3.png" class="img-fluid" alt="Logo" />
        </a>
      </div>
      <div class="header-menu">
        <div class="main-menu-wrapper">
          <div class="menu-header">
            <a [routerLink]="routes.index" class="menu-logo">
              <img src="assets/img/logo-3.png" class="img-fluid" alt="Logo" />
            </a>
            <a id="menu_close" (click)="hideSidebar()" class="menu-close" [routerLink]="">
              <i class="fas fa-times"></i
            ></a>
          </div>
          <ul class="main-nav">
            @for (mainMenus of header; track mainMenus; let i = $index) {
              <li
                class="has-submenu"
                routerLinkActive="active"
                [ngClass]="{
                  megamenu: mainMenus.tittle === 'Home' || mainMenus.tittle === 'Pages',
                }"
              >
                <a
                  [routerLink]=""
                  class="main-menu"
                  (click)="mainMenus.showAsTab = !mainMenus.showAsTab"
                  [ngClass]="{ submenu: openDropdownIndex === i }"
                  (click)="toggleSubMenu(i)"
                >
                  {{ mainMenus.tittle }}
                  <!-- Index-6 uses fa-plus instead of fa-chevron-down -->
                  <!-- <span
                  ><i
                    [ngClass]=""
                      base === 'index-4' ||
                      base === 'index-5' ||
                      base === 'index-6'
                        ? 'fa-solid fa-plus'
                        : 'fa-solid fa-chevron-down'
                    "
                  ></i
                ></span> -->
                </a>
              </li>
            }
          </ul>
          <div class="header-items">

            <div class="about-popup-item border-0 pb-0">
              <h3 class="title">Contact Information</h3>
              <div class="support-item mb-3">
                <div class="avatar avatar-lg bg-primary rounded-circle">
                  <i class="isax isax-messages-3"></i>
                </div>
                <div>
                  <p class="title">General Inquiries</p>
                  <h5 class="link">info@example.com</h5>
                </div>
              </div>
              <div class="support-item">
                <div class="avatar avatar-lg bg-primary rounded-circle">
                  <i class="isax isax-call-calling"></i>
                </div>
                <div>
                  <p class="title">Emergency Cases</p>
                  <h5 class="link">+1 24565 89856</h5>
                </div>
              </div>
            </div>

            <div class="about-popup-item border-0 pb-0">
              <h3 class="title">Follow Us</h3>
              <ul class="d-flex align-items-center gap-2 social-iyem">
                <li>
                  <a [routerLink]="" class="social-icon"
                    ><i class="fa-brands fa-facebook"></i
                  ></a>
                </li>
                <li>
                  <a [routerLink]="" class="social-icon"
                    ><i class="fa-brands fa-x-twitter"></i
                  ></a>
                </li>
                <li>
                  <a [routerLink]="" class="social-icon"
                    ><i class="fa-brands fa-instagram"></i
                  ></a>
                </li>
                <li>
                  <a [routerLink]="" class="social-icon"
                    ><i class="fa-brands fa-linkedin"></i
                  ></a>
                </li>
              </ul>
            </div>

            <div class="header-items-button">
              <a
                [routerLink]="routes.userLogin"
                class="btn btn-primary btn-primary-gradient"
                ><i class="isax isax-lock-1 me-2"></i>Logout</a
              >
            </div>
          </div>
        </div>
      </div>

      <!-- Book Appointment + CTA Toggles -->
      <ul class="nav header-navbar-rht align-items-center cta-tabs">
        <li>
          <a [routerLink]="routes.mapGrid" class="theme-btn btn-md btn-primary">
            <i class="isax isax-user-add me-2"></i><span>Book an Appointment</span>
          </a>
          <!-- <a href="https://client.vetllama.com/authentication/register" class="theme-btn btn-md btn-primary">
            <i class="isax isax-user-add me-2"></i><span>Get Started</span>
          </a> -->
        </li>
        <li
          class="cta-pill"
          [ngClass]="{ active: selectedCTA === 'order' }"
          style="top: -23px; left: -342px"
        >
          <a (click)="selectCTA('order')">Pet parents</a>
        </li>
        <li
          class="cta-pill"
          [ngClass]="{ active: selectedCTA === 'consult' }"
          style="top: -23px; left: -240px"
        >
          <a (click)="selectCTA('consult')">Veterinarians</a>
           <!-- <a href="https://client.vetllama.com/authentication/register" target="_blank" rel="noopener noreferrer">Veterinarians</a> -->
        </li>
      </ul>
    </nav>
  </div>
</header>

// react-app/src/components/Header.tsx
import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

export default function Header(): JSX.Element {
  const [searchField, setSearchField] = useState(false)
  const [selectedCTA, setSelectedCTA] = useState<'order'|'consult'>('order')
  const [isFixed, setIsFixed] = useState(false)
  const [openDropdownIndex, setOpenDropdownIndex] = useState<number|null>(null)
  const navigate = useNavigate()

  useEffect(() => {
    const onScroll = () => {
      const scroll = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0
      setIsFixed(window.pageYOffset > 50)
      const headerOne = document.querySelector('.header-one')
      if (headerOne && scroll > 35) headerOne.classList.add('header-space')
      else if (headerOne) headerOne.classList.remove('header-space')

      const headerTen = document.querySelector('.header-ten')
      if (headerTen && scroll > 35) headerTen.classList.add('header-space')
      else if (headerTen) headerTen.classList.remove('header-space')
    }
    window.addEventListener('scroll', onScroll)
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const toggleSubMenu = (i: number) => setOpenDropdownIndex(openDropdownIndex === i ? null : i)
  const toggleSearch = () => setSearchField(!searchField)
  const selectCTA = (cta: 'order'|'consult') => {
    setSelectedCTA(cta)
    if (cta === 'order') navigate('/')
    else navigate('/vet-registration')
  }

  return (
    <header className={`header header-custom header-default inner-header header-fixed relative ${isFixed ? 'fixed' : ''}`}>
      <div className="container">
        <nav className="navbar navbar-expand-lg header-nav">
          <div className="navbar-header">
            <a id="mobile_btn" onClick={() => document.body.classList.toggle('sidebar-open')}>
              <i className="fa-solid fa-bars"></i>
            </a>
            <Link to="/" className="navbar-brand logo">
              <img src="/assets/img/logo-3.png" className="img-fluid" alt="Logo" />
            </Link>
          </div>

          <div className="header-menu">
            <div className="main-menu-wrapper">
              <div className="menu-header">
                <Link to="/" className="menu-logo">
                  <img src="/assets/img/logo-3.png" className="img-fluid" alt="Logo" />
                </Link>
                <a id="menu_close" onClick={() => document.body.classList.remove('sidebar-open')} className="menu-close">
                  <i className="fas fa-times"></i>
                </a>
              </div>

              <ul className="main-nav">
                <li className="has-submenu">
                  <a className="main-menu" onClick={() => toggleSubMenu(0)}>
                    Home
                  </a>
                </li>
              </ul>

              <div className="header-items">
                <div className="about-popup-item border-0 pb-0">
                  <h3 className="title">Contact Information</h3>
                  <div className="support-item mb-3">
                    <div className="avatar avatar-lg bg-primary rounded-circle">
                      <i className="isax isax-messages-3"></i>
                    </div>
                    <div>
                      <p className="title">General Inquiries</p>
                      <h5 className="link">info@example.com</h5>
                    </div>
                  </div>
                  <div className="support-item">
                    <div className="avatar avatar-lg bg-primary rounded-circle">
                      <i className="isax isax-call-calling"></i>
                    </div>
                    <div>
                      <p className="title">Emergency Cases</p>
                      <h5 className="link">+1 24565 89856</h5>
                    </div>
                  </div>
                </div>

                <div className="about-popup-item border-0 pb-0">
                  <h3 className="title">Follow Us</h3>
                  <ul className="d-flex align-items-center gap-2 social-iyem">
                    <li><a href="#" className="social-icon"><i className="fa-brands fa-facebook"></i></a></li>
                    <li><a href="#" className="social-icon"><i className="fa-brands fa-twitter"></i></a></li>
                    <li><a href="#" className="social-icon"><i className="fa-brands fa-instagram"></i></a></li>
                    <li><a href="#" className="social-icon"><i className="fa-brands fa-linkedin"></i></a></li>
                  </ul>
                </div>

                <div className="header-items-button">
                  <Link to="/user-login" className="btn btn-primary btn-primary-gradient"><i className="isax isax-lock-1 me-2"></i>Logout</Link>
                </div>
              </div>
            </div>
          </div>

          <ul className="nav header-navbar-rht align-items-center cta-tabs">
            <li>
              <Link to="/map-grid" className="theme-btn btn-md btn-primary"><i className="isax isax-user-add me-2"></i><span>Book an Appointment</span></Link>
            </li>
            <li className={`cta-pill ${selectedCTA === 'order' ? 'active' : ''}`} style={{ top: -23, left: -342 }}>
              <a onClick={() => selectCTA('order')}>Pet parents</a>
            </li>
            <li className={`cta-pill ${selectedCTA === 'consult' ? 'active' : ''}`} style={{ top: -23, left: -240 }}>
              <a onClick={() => selectCTA('consult')}>Veterinarians</a>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  )
}
