// src/app/pages/doctors/map-grid/map-grid.component.ts
/* eslint-disable @typescript-eslint/no-unused-vars */

import { Component, OnInit } from '@angular/core';
import { GoogleMapsModule } from '@angular/google-maps';
import { MatSelectModule } from '@angular/material/select';
import { RouterLink } from '@angular/router';
import { routes } from 'src/app/core/routes/routes';
import { CommonService } from 'src/app/core/services/common/common.service';
import { BreadcrumbSearchComponent } from 'src/app/shared/breadcrumb-search/breadcrumb-search.component';
interface data {
  value: string;
}

@Component({
  selector: 'app-map-grid',
  templateUrl: './map-grid.component.html',
  styleUrls: ['./map-grid.component.scss'],
  imports: [
    RouterLink,
    GoogleMapsModule,
    BreadcrumbSearchComponent,
    MatSelectModule,
  ],
})
export class MapGridComponent implements OnInit {
  public routes = routes;
  public base = 'index-6';

  constructor(private commonService: CommonService) {
    this.commonService.base.next('index-6');
  }
  public isClassAdded: boolean[] = [false];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  slider: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private infowindow!: google.maps.InfoWindow;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  doc_name: any;
  private bounds = new google.maps.LatLngBounds();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  map: any;
  current = 0;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  content: any;

  locations = [
    {
      id: 1,
      doc_name: 'Dr. Ruby Perrin',
      speciality: 'Psychologist',
      address: 'Florida, USA',
      nextavailable: 'Available on Fri, 22 Mar',
      amount: '$300 - $1000',
      lat: 53.470692,
      lng: -2.220328,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '17',
      image: 'assets/img/doctors/doctor-01.jpg',
    },
    {
      id: 2,
      doc_name: 'Dr. Darren Elder',
      speciality: 'Psychologist',
      address: 'Newyork, USA',
      nextavailable: 'Available on Fri, 23 Mar',
      amount: '$50 - $300',
      lat: 53.469189,
      lng: -2.199262,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '35',
      image: 'assets/img/doctors/doctor-02.jpg',
    },
    {
      id: 3,
      doc_name: 'Dr. Deborah Angel',
      speciality: 'Psychologist',
      address: 'Georgia, USA',
      nextavailable: 'Available on Fri, 23 Mar',
      amount: '"$100 - $400',
      lat: 53.468665,
      lng: -2.189269,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '27',
      image: 'assets/img/doctors/doctor-03.jpg',
    },
    {
      id: 4,
      doc_name: 'Dr. Sofia Brient',
      speciality: 'Psychologist',
      address: 'Louisiana, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$150 - $250',
      lat: 53.463894,
      lng: -2.17788,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '4',
      image: 'assets/img/doctors/doctor-04.jpg',
    },
    {
      id: 5,
      doc_name: 'Dr. Marvin Campbell',
      speciality: 'Psychologist',
      address: 'Michigan, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$50 - $700',
      lat: 53.466359,
      lng: -2.213314,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '66',
      image: 'assets/img/doctors/doctor-05.jpg',
    },
    {
      id: 6,
      doc_name: 'Dr. Katharine Berthold',
      speciality: 'Psychologist',
      address: 'Texas, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$100 - $500',
      lat: 53.463906,
      lng: -2.213271,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '52',
      image: 'assets/img/doctors/doctor-06.jpg',
    },
    {
      id: 7,
      doc_name: 'Dr. Linda Tobin',
      speciality: 'Psychologist',
      address: 'Kansas, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$100 - $1000',
      lat: 53.461974,
      lng: -2.210661,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '43',
      image: 'assets/img/doctors/doctor-07.jpg',
    },
    {
      id: 8,
      doc_name: 'Dr. Paul Richard',
      speciality: 'Psychologist',
      address: 'California, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$100 - $1000',
      lat: 53.458785,
      lng: -2.188532,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '49',
      image: 'assets/img/doctors/doctor-08.jpg',
    },
    {
      id: 9,
      doc_name: ' Dr. John Gibbs',
      speciality: 'Psychologist',
      address: 'Oklahoma, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '"$500 - $2500',
      lat: 53.4558571,
      lng: -2.1950372,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '112',
      image: 'assets/img/doctors/doctor-09.jpg',
    },
    {
      id: 10,
      doc_name: 'Dr. Olga Barlow',
      speciality: 'Psychologist',
      address: 'Montana, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$75 - $250',
      lat: 53.45885,
      lng: -2.194549,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '65',
      image: 'assets/img/doctors/doctor-10.jpg',
    },
    {
      id: 11,
      doc_name: ' Dr. Julia Washington',
      speciality: 'Psychologist',
      address: 'Oklahoma, USA',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$275 - $450',
      lat: 53.461733,
      lng: -2.194502,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '5',
      image: 'assets/img/doctors/doctor-11.jpg',
    },
    {
      id: 12,
      doc_name: ' Dr. Shaun Aponte',
      speciality: 'Psychologist',
      nextavailable: 'Available on Fri, 25 Mar',
      amount: '$275 - $450',
      address: 'Indiana, USA',
      lat: 53.460548,
      lng: -2.190956,
      icons: 'default',
      profile_link: 'profile.html',
      total_review: '5',
      image: 'assets/img/doctors/doctor-12.jpg',
    },
  ];
  images = [
    {
      path: 'assets/img/features/feature-01.jpg',
    },
    {
      path: 'assets/img/features/feature-02.jpg',
    },
    {
      path: 'assets/img/features/feature-03.jpg',
    },
    {
      path: 'assets/img/features/feature-04.jpg',
    },
  ];
  ngOnInit(): void {
    this.initilize();
    if (!sessionStorage.getItem('pageReloaded')) {
      sessionStorage.setItem('pageReloaded', 'true');
      window.location.reload();
    } else {
      sessionStorage.removeItem('pageReloaded'); // Reset for future reloads
      this.initilize();
    }
  }
  show() {
    this.infowindow.close();
    if (!this.map.slide) {
      return;
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let next: any;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let marker: any;
    if (this.locations.length == 0) {
      return;
    } else if (this.locations.length == 1) {
      next = 0;
    }
    if (this.locations.length > 1) {
      do {
        next = Math.floor(Math.random() * this.locations.length);
      } while (next == this.current);
    }
    this.current = next;
    // eslint-disable-next-line prefer-const
    marker = this.locations[next];
    this.setInfo(marker);
    this.infowindow.open(this.map, marker);
  }
  initilize() {
    const mapOptions: google.maps.MapOptions = {
      zoom: 14,
      center: new google.maps.LatLng(53.470692, -2.220328),
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
    };
    this.map = new google.maps.Map(
      document.getElementById('map') as HTMLElement,
      mapOptions,
    );
    this.map['slide'] = true;
    this.infowindow = new google.maps.InfoWindow({ content: 'loading...' });
    google.maps.event.addListener(this.infowindow, 'closeclick', () => {
      this.infowindow.close();
    });
    this.map.slide = true;

    this.setMarkers(this.map, this.locations);
    this.infowindow = new google.maps.InfoWindow({
      content: 'loading...',
    });
    // google.maps.event.addListener(this.infowindow, 'closeclick', function () {
    //   this.infowindow.close();
    // });
    // this.slider = window.setTimeout(this.show, 3000);
  }
  setInfo(marker: {
    profile_link: string;
    next_available: string;
    doc_name: string;
    total_review: string;
    speciality: string;
    image: string;
    amount: string;
    address: string;
  }) {
    const content =
      '<div class="card border-0" style="width: 100%; display: inline-block;">' +
      '<div class="card-body">' +
      '<div class="doc-img d-flex align-items-center">' +
      '<a href="' +
      marker.profile_link +
      '" class="avatar flex-shrink-0 me-2 avatar-xl avatar-rounded" tabindex="0" target="_blank">' +
      '<img class="img-fluid" alt="' +
      marker.doc_name +
      '" src="' +
      marker.image +
      '">' +
      '</a>' +
      '<div>' +
      '<h6 class="title fs-16 mb-1">' +
      '<a href="' +
      marker.profile_link +
      '" tabindex="0">' +
      marker.doc_name +
      '</a>' +
      '<span class="badge bg-orange mt-1"><i class="fa-solid fa-star me-1"></i>5.0</span>' +
      '</h6>' +
      '<p class="speciality text-indigo">' +
      marker.speciality +
      '</p>' +
      '</div>' +
      '</div>' +
      '<div class="pro-content">' +
      '<ul class="available-info">' +
      '<li><i class="fas fa-map-marker-alt"></i> ' +
      marker.address +
      ' </li>' +
      '</ul>' +
      '</div>' +
      '</div>' +
      '</div>';
    this.infowindow.setContent(content);
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  setMarkers(map: any, locations: any) {
    for (let i = 0; i < locations.length; i++) {
      const item = locations[i];
      const latlng = new google.maps.LatLng(item.lat, item.lng);
      const marker = new google.maps.Marker({
        position: latlng,
        map: map,

        icon: 'assets/img/marker.png',
      });
      this.bounds.extend(latlng);

      google.maps.event.addListener(marker, 'click', () => {
        this.setInfo(item);
        this.infowindow.open(map, marker);
      });
    }
    map.fitBounds(this.bounds);
    google.maps.event.addListener(map, 'zoom_changed', function () {
      if (map.zoom > 16) map.slide = false;
    });
  }
  toggleClass(index: number) {
    this.isClassAdded[index] = !this.isClassAdded[index];
  }
}

// src/react-components/MapGrid.jsx
import React, { useEffect, useRef } from 'react';
import BreadcrumbSearch from './BreadcrumbSearch';
import { useNavigate } from 'react-router-dom';

const locations = [
  { id: 1, doc_name: 'Dr. Ruby Perrin', speciality: 'Psychologist', address: 'Florida, USA', nextavailable: 'Available on Fri, 22 Mar', amount: '$300 - $1000', lat: 53.470692, lng: -2.220328, image: '/assets/img/doctors/doctor-01.jpg' },
  { id: 2, doc_name: 'Dr. Darren Elder', speciality: 'Psychologist', address: 'Newyork, USA', nextavailable: 'Available on Fri, 23 Mar', amount: '$50 - $300', lat: 53.469189, lng: -2.199262, image: '/assets/img/doctors/doctor-02.jpg' },
  // ... truncated for brevity; add others as needed
];

export default function MapGrid() {
  const mapRef = useRef(null);
  const mapInstance = useRef(null);
  const boundsRef = useRef(null);
  const infowindowRef = useRef(null);
  const navigate = useNavigate();

  useEffect(() => {
    // set a base marker initialization similar to Angular component
    const initMap = () => {
      if (!window.google) return;
      const mapOptions = {
        zoom: 14,
        center: new window.google.maps.LatLng(53.470692, -2.220328),
        scrollwheel: false,
        mapTypeId: window.google.maps.MapTypeId.ROADMAP,
      };
      mapInstance.current = new window.google.maps.Map(document.getElementById('map'), mapOptions);
      boundsRef.current = new window.google.maps.LatLngBounds();
      infowindowRef.current = new window.google.maps.InfoWindow({ content: 'loading...' });
      setMarkers(mapInstance.current, locations);
      mapInstance.current.fitBounds(boundsRef.current);
      window.google.maps.event.addListener(mapInstance.current, 'zoom_changed', () => {
        if (mapInstance.current.getZoom() > 16) mapInstance.current.slide = false;
      });
    };

    const setMarkers = (map, locs) => {
      locs.forEach((item) => {
        const latlng = new window.google.maps.LatLng(item.lat, item.lng);
        const marker = new window.google.maps.Marker({ position: latlng, map, icon: '/assets/img/marker.png' });
        boundsRef.current.extend(latlng);
        marker.addListener('click', () => {
          setInfo(item);
          infowindowRef.current.open(map, marker);
        });
      });
    };

    const setInfo = (marker) => {
      const content = `
        <div class="card border-0" style="width:100%;display:inline-block;">
          <div class="card-body">
            <div class="doc-img d-flex align-items-center">
              <a href="${marker.profile_link || '#'}" class="avatar flex-shrink-0 me-2 avatar-xl avatar-rounded" target="_blank">
                <img class="img-fluid" alt="${marker.doc_name}" src="${marker.image}" />
              </a>
              <div>
                <h6 class="title fs-16 mb-1"><a href="${marker.profile_link || '#'}">${marker.doc_name}</a><span class="badge bg-orange mt-1"><i class="fa-solid fa-star me-1"></i>5.0</span></h6>
                <p class="speciality text-indigo">${marker.speciality}</p>
              </div>
            </div>
            <div class="pro-content"><ul class="available-info"><li><i class="fas fa-map-marker-alt"></i> ${marker.address}</li></ul></div>
          </div>
        </div>`;
      infowindowRef.current.setContent(content);
    };

    // Wait until google maps is available
    if (window.google && window.google.maps) initMap();
    else {
      // Try to load maps if script tag exists on page elsewhere
      const interval = setInterval(() => {
        if (window.google && window.google.maps) {
          clearInterval(interval);
          initMap();
        }
      }, 500);
      return () => clearInterval(interval);
    }
  }, []);

  return (
    <>
      <BreadcrumbSearch />
      <div className="content top-space pet-bg">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-md-6"><h3 className="main-title">Showing <span className="text-secondary">450</span> Doctors For You</h3></div>
            <div className="col-md-6">
              <div className="d-flex align-items-center justify-content-end mb-4">
                <div className="dropdown header-dropdown me-2">
                  <a className="dropdown-toggle sort-dropdown" data-bs-toggle="dropdown" href="#"> <span>Sort By</span>Price (Low to High)</a>
                  <div className="dropdown-menu dropdown-menu-end">
                    <a href="#" className="dropdown-item"> Price (Low to High) </a>
                    <a href="#" className="dropdown-item"> Price (High to Low) </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="row">
            <div className="col-lg-9">
              {/* Filters and listings omitted for brevity - render static card example */}
              <div className="row">
                <div className="col-xxl-4 col-md-6">
                  <div className="card">
                    <div className="card-img card-img-hover">
                      <img src="/assets/img/doctor-grid/doctor-grid-011.webp" alt="" />
                      <div className="grid-overlay-item d-flex align-items-center justify-content-between"><span className="badge bg-orange"><i className="fa-solid fa-star me-1"></i>5.0</span><a href="#" className="fav-icon"><i className="fa fa-heart"></i></a></div>
                    </div>
                    <div className="card-body p-0">
                      <div className="d-flex active-bar align-items-center justify-content-between p-3"><a className="text-indigo fw-medium fs-14">Psychologist</a><span className="badge bg-success-light d-inline-flex align-items-center"><i className="fa-solid fa-circle fs-5 me-1"></i>Available</span></div>
                      <div className="p-3 pt-0">
                        <div className="doctor-info-detail mb-3 pb-3"><h3 className="mb-1"><a>Dr. Michael Brown</a></h3><div className="d-flex align-items-center"><p className="d-flex align-items-center mb-0 fs-14"><i className="isax isax-location me-2"></i>Minneapolis, MN</p><i className="fa-solid fa-circle fs-5 text-primary mx-2 me-1"></i><span className="fs-14 fw-medium">30 Min</span></div></div>
                        <div className="d-flex align-items-center justify-content-between"><div><p className="mb-1">Consultation Fees</p><h3 className="text-orange">$650</h3></div><a href="/booking" className="theme-btn btn-primary"><span><i className="isax isax-calendar-1 me-2"></i> Book Now</span></a></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div className="col-lg-3 map-right">
              <div id="map" ref={mapRef} style={{ width: '100%', height: '600px' }} />
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
