// src/app/features/pages/patients/common/breadcrumb-search/breadcrumb-search.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
import { routes } from 'src/app/core/routes/routes';
import { CommonService } from 'src/app/core/services/common/common.service';

@Component({
  selector: 'app-breadcrumb-search',
  templateUrl: './breadcrumb-search.component.html',
  styleUrls: ['./breadcrumb-search.component.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule, BsDatepickerModule],
})
export class BreadcrumbSearchComponent {
  public routes = routes;

  base = '';
  page = '';
  last = '';
  constructor(
    private common: CommonService,
    private router: Router,
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res?.replaceAll('-', ' ');
    });
    this.common.page.subscribe((res: string) => {
      console.warn('ssss', res);
      if (res === 'chat') {
        this.page = 'Message';
      } else if (res === 'appointments') {
        this.page = 'Patient Appointments';
      } else if (res === 'patient-accounts') {
        this.page = 'Accounts';
      } else if (res === 'patient-invoice') {
        this.page = 'Invoices';
      } else if (res === 'doctors') {
        this.page = 'Book Appointment';
      } else {
        this.last = this.page;
        this.page = res?.replaceAll('-', ' ');
      }
    });
    this.common.last.subscribe((res: string) => {
      this.last = res?.replaceAll('-', ' ');
    });
  }
  onSubmit(): void {
    this.router.navigateByUrl('/patients/search-doctor/search1');
  }
}

<!-- Breadcrumb -->
<div class="breadcrumb-bar overflow-visible">
  <div class="container">
    <div class="row align-items-center inner-banner">
      <div class="col-md-12 col-12 text-center">
        <nav aria-label="breadcrumb" class="page-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a [href]="routes.index"><i class="isax isax-home-15"></i></a>
            </li>
            <li class="breadcrumb-item">{{ page | titlecase }}</li>
            <!-- <li class="breadcrumb-item active" aria-current="page">
              {{ last | titlecase }}
            </li> -->
          </ol>
          <!-- <h2 class="breadcrumb-title">{{ last | titlecase }}</h2> -->
        </nav>
      </div>
    </div>
    <div class="bg-primary-gradient rounded-pill doctors-search-box">
      <div class="search-box-one rounded-pill">
        <form (ngSubmit)="onSubmit()">
          <div class="search-input search-line">
            <i class="isax isax-hospital5 bficon"></i>
            <div class="mb-0">
              <input
                type="text"
                class="form-control"
                placeholder="Search for Doctors, Hospitals, Clinics"
              />
            </div>
          </div>
          <div class="search-input search-map-line">
            <i class="isax isax-location5"></i>
            <div class="mb-0">
              <input type="text" class="form-control" placeholder="Location" />
            </div>
          </div>
          <div class="search-input search-calendar-line">
            <i class="isax isax-calendar-tick5"></i>
            <div class="mb-0">
              <input
                type="text"
                class="form-control datetimepicker"
                placeholder="Date"
                bsDatepicker
                [bsConfig]="{ adaptivePosition: true }"
              />
            </div>
          </div>
          <div class="form-search-btn">
            <button
              class="btn btn-primary d-inline-flex align-items-center rounded-pill"
              type="submit"
            >
              <i class="isax isax-search-normal-15 me-2"></i>Search
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="breadcrumb-bg">
    <img src="assets/img/bg/image1.png" alt="img" class="breadcrumb-bg-01" />
    <img src="assets/img/bg/image2.png" alt="img" class="breadcrumb-bg-02" />
    <img
      src="assets/img/bg/breadcrumb-icon.png"
      alt="img"
      class="breadcrumb-bg-03"
    />
    <img
      src="assets/img/bg/breadcrumb-icon.png"
      alt="img"
      class="breadcrumb-bg-04"
    />
  </div>
</div>
<!-- /Breadcrumb -->

// src/components/BreadCrumbSearch.tsx
import React, { type JSX } from 'react'
import { useNavigate } from 'react-router-dom'

export default function BreadcrumbSearch(): JSX.Element {
  const navigate = useNavigate()
  const onSubmit = (e: React.FormEvent) => { e.preventDefault(); navigate('/patients/search-doctor/search1') }
  return (
    <div className="breadcrumb-bar overflow-visible">
      <div className="container">
        <div className="row align-items-center inner-banner">
          <div className="col-md-12 col-12 text-center">
            <nav aria-label="breadcrumb" className="page-breadcrumb">
              <ol className="breadcrumb">
                <li className="breadcrumb-item"><a href="/"><i className="isax isax-home-15"></i></a></li>
                <li className="breadcrumb-item">Book Appointment</li>
              </ol>
            </nav>
          </div>
        </div>
        <div className="bg-primary-gradient rounded-pill doctors-search-box">
          <div className="search-box-one rounded-pill">
            <form onSubmit={onSubmit}>
              <div className="search-input search-line">
                <i className="isax isax-hospital5 bficon"></i>
                <div className="mb-0"><input type="text" className="form-control" placeholder="Search for Doctors, Hospitals, Clinics"/></div>
              </div>
              <div className="search-input search-map-line">
                <i className="isax isax-location5"></i>
                <div className="mb-0"><input type="text" className="form-control" placeholder="Location"/></div>
              </div>
              <div className="search-input search-calendar-line">
                <i className="isax isax-calendar-tick5"></i>
                <div className="mb-0"><input type="text" className="form-control" placeholder="Date"/></div>
              </div>
              <div className="form-search-btn">
                <button className="btn btn-primary d-inline-flex align-items-center rounded-pill" type="submit"><i className="isax isax-search-normal-15 me-2"></i>Search</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div className="breadcrumb-bg">
        <img src="/assets/images/bg/image1.png" alt="img" className="breadcrumb-bg-01" />
        <img src="/assets/images/bg/image2.png" alt="img" className="breadcrumb-bg-02" />
        <img src="/assets/images/bg/breadcrumb-icon.png" alt="img" className="breadcrumb-bg-03" />
        <img src="/assets/images/bg/breadcrumb-icon.png" alt="img" className="breadcrumb-bg-04" />
      </div>
    </div>
  )
}
